# Generated by Django 3.1.7 on 2021-04-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0038_manifest'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='camera',
            field=models.CharField(default='', max_length=128),
        ),
    ]
