# Generated by Django 3.1.7 on 2021-04-09 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0039_image_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='', max_length=1024)),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calibfile', to='engine.data')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
